default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: root
  password: 256391
  host: localhost
  port: 5432

development:
  <<: *default
  database: match_0

test:
  <<: *default
  database: match_0

production:
  <<: *default
  database: match_0
